site_name: Cloud and Devops 
nav:
    - Home: index.md
    - About Me: about.md
    - DevOps: new.md
    - K8S Concepts: k8s.md
    - K8S Administraton: k8sadmin.md
    - K3S: k3s.md
    - Ansible: ansible.md

